spring.application.name=cvcreator

spring.datasource.url=jdbc:postgresql://localhost:5432/cvcreator
spring.datasource.username=postgres
spring.datasource.password=kwakwa5!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

app.encryption.secret=12345678901234567890123456789012
jwt.secret=4932c6c8e29d4020b55c185726f1e3ab4932c6c8e29d4020b55c185726f1e3ab

spring.security.user.name=admin
spring.security.user.password=kwakwa5!

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.OncePerRequestFilter=DEBUG

gemini.api.key=AIzaSyDjPEVrNM5pUY47W1fgHB9Hy14J9PRgHBY
gemini.model=models/gemini-2.5-flash
gemini.url=https://generativelanguage.googleapis.com/v1

logging.level.org.springframework.web=DEBUG